# Generated by Django 4.2.7 on 2023-12-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_size_product_deep_product_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.FileField(upload_to='products/', verbose_name='Изображения'),
        ),
    ]
