# Generated by Django 4.2.7 on 2023-12-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_review_author_remove_review_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254, verbose_name='Е-майл'),
        ),
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(default='', max_length=250, verbose_name='Сообщение'),
        ),
    ]
